const app=document.querySelector('#app');
const riders=[
 {id:1,name:'Alex Rider',city:'Madrid',status:'Activo ahora',state:'green',left:'48%',top:'39%',board:'eSkate SUV',km:'1.240 km'},
 {id:2,name:'Marta',city:'Valencia',status:'Última conexión: hace 2 h',state:'red',left:'70%',top:'51%',board:'Electric Rider',km:'860 km'},
 {id:3,name:'Dani',city:'Sevilla',status:'Activo ahora',state:'green',left:'27%',top:'58%',board:'eSkate',km:'2.105 km'}
];
function shell(body){app.innerHTML='<section class="phone">'+body+'</section>'}
function home(){shell(`<div class="brand">E-SKATE SUV</div><h1>Comunidad Rider</h1><p class="sub">Conecta, rueda y comparte.</p>
${[['🎙️','Rider Voz','Conversación entre riders durante la ruta.'],['📍','Riders en mi zona','Descubre riders activos y contactos cercanos.'],['🗺️','Rutas compartidas','Descubre y comparte rutas de la comunidad.'],['🏆','Retos','Retos de distancia, desnivel y exploración.']].map((x,i)=>`<div class="card" data-menu="${i}"><div class="row"><div class="icon">${x[0]}</div><div><h3>${x[1]}</h3><p>${x[2]}</p></div></div></div>`).join('')}`);
document.querySelector('[data-menu="1"]').onclick=consent}
function consent(){shell(`<div class="brand">RIDERS EN MI ZONA</div><h1>Privacidad primero</h1><div class="card"><div class="row"><div><h3>Compartir mi ubicación</h3><p>Activa esta opción para aparecer en la comunidad. Puedes desactivarla cuando quieras.</p></div><div class="switch" id="sw"><div class="knob"></div></div></div><div id="consent" class="hidden"><p class="sub">Tu ubicación se utiliza para mostrarte en el mapa. La última ubicación podrá mostrarse temporalmente cuando dejes de estar activo.</p><button class="btn" id="accept">ACEPTO Y ACTIVAR</button></div></div><button class="btn secondary" id="back">Volver</button>`);
sw.onclick=()=>{sw.classList.add('on');document.querySelector('#consent').classList.remove('hidden')};accept.onclick=map;back.onclick=home}
function map(){shell(`<div class="brand">RIDERS EN MI ZONA</div><div class="row spread"><h1>España</h1><button class="mini" id="back">‹</button></div><div class="legend"><span>🟢 Activo</span><span>🔴 Última ubicación</span><span>🔵 Tú</span></div><div class="map"><div class="spain"></div>${riders.map(r=>`<button class="dot ${r.state}" data-rider="${r.id}" style="left:${r.left};top:${r.top}"></button>`).join('')}<i class="dot cyan" style="left:52%;top:56%"></i></div><p class="sub center">Toca un rider para ver su perfil.</p>`);
back.onclick=home;document.querySelectorAll('[data-rider]').forEach(b=>b.onclick=()=>profile(+b.dataset.rider))}
function profile(id){const r=riders.find(x=>x.id===id);shell(`<div class="brand">RIDER</div><button class="mini" id="back">‹ Mapa</button><div class="profileAvatar">🛹</div><h1 class="center">${r.name}</h1><p class="center ${r.state==='green'?'online':'offline'}">● ${r.status}</p><div class="card"><h3>${r.city}</h3><p>Tabla: ${r.board}</p><p>Distancia compartida: ${r.km}</p></div><button class="btn" id="message">💬 Enviar mensaje</button>`);back.onclick=map;message.onclick=()=>chat(r)}
function chat(r){shell(`<div class="row spread"><div><div class="brand">CHAT PRIVADO</div><h2>${r.name}</h2></div><button class="mini" id="back">‹</button></div><div class="chat"><div class="bubble them">¿Qué tal? ¿Sales hoy?</div><div class="bubble me">Sí, estaba mirando una ruta 👋</div></div><button class="btn voice" id="voice">🎙️ Invitar a Rider Voz</button><div class="composer"><input id="msg" placeholder="Escribe un mensaje..."><button id="send">➤</button></div>`);back.onclick=()=>profile(r.id);send.onclick=()=>{if(msg.value.trim()){document.querySelector('.chat').insertAdjacentHTML('beforeend',`<div class="bubble me">${msg.value.replace(/[<>]/g,'')}</div>`);msg.value=''}};voice.onclick=()=>alert('Invitación a Rider Voz preparada')}
home();