const app=document.querySelector('#app');
const state={locationConsent:localStorage.getItem('cr_location_consent')==='yes',locationSharing:localStorage.getItem('cr_location_sharing')==='yes'};
const KEY='comunidad_rider_v1';
function dbLoad(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function dbSave(db){localStorage.setItem(KEY,JSON.stringify(db))}
function savedMessages(id){return (dbLoad().messages||{})[id]||[]}
function saveMessage(id,text){const db=dbLoad();db.messages=db.messages||{};db.messages[id]=db.messages[id]||[];db.messages[id].push({text,from:'me',at:new Date().toISOString()});dbSave(db)}
function isFavorite(id){return (dbLoad().favoriteRoutes||[]).includes(id)}
function toggleFavorite(id){const db=dbLoad();db.favoriteRoutes=db.favoriteRoutes||[];const i=db.favoriteRoutes.indexOf(id);i<0?db.favoriteRoutes.push(id):db.favoriteRoutes.splice(i,1);dbSave(db);return db.favoriteRoutes.includes(id)}
function joinedChallenge(id){return (dbLoad().joinedChallenges||[]).includes(id)}
function joinChallenge(id){const db=dbLoad();db.joinedChallenges=db.joinedChallenges||[];if(!db.joinedChallenges.includes(id))db.joinedChallenges.push(id);dbSave(db)}
function saveState(){localStorage.setItem('cr_location_consent',state.locationConsent?'yes':'no');localStorage.setItem('cr_location_sharing',state.locationSharing?'yes':'no')}
function requestLocation(done){if(!navigator.geolocation){done&&done(null);return}navigator.geolocation.getCurrentPosition(p=>done&&done({lat:p.coords.latitude,lng:p.coords.longitude}),()=>done&&done(null),{enableHighAccuracy:true,timeout:8000,maximumAge:30000})}
const riders=[
{id:1,name:'Alex Rider',city:'Madrid',status:'Activo ahora',state:'green',left:'48%',top:'39%',board:'eSkate SUV',km:'1.240 km'},
{id:2,name:'Marta',city:'Valencia',status:'Última conexión: hace 2 h',state:'red',left:'70%',top:'51%',board:'Electric Rider',km:'860 km'},
{id:3,name:'Dani',city:'Sevilla',status:'Activo ahora',state:'green',left:'27%',top:'58%',board:'eSkate',km:'2.105 km'}];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function shell(body){app.innerHTML='<section class="phone">'+body+'</section>'}
function home(){shell(`<div class="brand">E-SKATE SUV</div><h1>Comunidad Rider</h1><p class="sub">Conecta, rueda y comparte.</p>
${[['🎙️','Rider Voz','Conversación entre riders durante la ruta.'],['📍','Riders en mi zona','Descubre riders activos y contactos cercanos.'],['🗺️','Rutas compartidas','Descubre y comparte rutas de la comunidad.'],['🏆','Retos','Retos de distancia, desnivel y exploración.'],['👤','Mi perfil Rider','Tu identidad dentro de la comunidad.']].map((x,i)=>`<button class="card menuCard" data-menu="${i}"><span class="row"><span class="icon">${x[0]}</span><span><strong>${x[1]}</strong><small>${x[2]}</small></span></span></button>`).join('')}`);
document.querySelector('[data-menu="0"]').onclick=riderVoice;document.querySelector('[data-menu="1"]').onclick=consent;document.querySelector('[data-menu="2"]').onclick=sharedRoutes;document.querySelector('[data-menu="3"]').onclick=challenges;document.querySelector('[data-menu="4"]').onclick=myProfile}
function consent(){if(state.locationConsent&&state.locationSharing){map();return}shell(`<div class="brand">RIDERS EN MI ZONA</div><h1>Privacidad primero</h1><div class="card"><div class="row"><div><h3>Compartir mi ubicación</h3><p>Activa esta opción para aparecer en la comunidad. Puedes desactivarla cuando quieras.</p></div><button class="switch" id="sw" aria-label="Compartir ubicación"><span class="knob"></span></button></div><div id="consent" class="hidden"><p class="sub">Tu ubicación se utiliza para mostrarte en el mapa. La última ubicación podrá mostrarse temporalmente cuando dejes de estar activo.</p><button class="btn" id="accept">ACEPTO Y ACTIVAR</button></div></div><button class="btn secondary" id="back">Volver</button>`);
const sw=document.querySelector('#sw'), box=document.querySelector('#consent');
sw.onclick=()=>{sw.classList.add('on');box.classList.remove('hidden')};document.querySelector('#accept').onclick=()=>{state.locationConsent=true;state.locationSharing=true;saveState();requestLocation(()=>map())};document.querySelector('#back').onclick=home}
function map(){shell(`<div class="brand">RIDERS EN MI ZONA</div><div class="row spread"><h1>España</h1><button class="mini" id="back">‹</button></div><div class="legend"><span>🟢 Activo</span><span>🔴 Última ubicación</span><span>🔵 Tú</span></div><div class="map"><div class="spain"></div>${riders.map(r=>`<button aria-label="${esc(r.name)}" class="dot ${r.state}" data-rider="${r.id}" style="left:${r.left};top:${r.top}"></button>`).join('')}<i class="dot cyan" style="left:52%;top:56%"></i></div><p class="sub center">Toca un rider para ver su perfil.</p><button class="btn secondary" id="privacy">⚙️ Privacidad de ubicación</button>`);
document.querySelector('#back').onclick=home;document.querySelector('#privacy').onclick=privacy;document.querySelectorAll('[data-rider]').forEach(b=>b.onclick=()=>profile(+b.dataset.rider))}
function profile(id){const r=riders.find(x=>x.id===id);shell(`<div class="brand">RIDER</div><button class="mini" id="back">‹ Mapa</button><div class="profileAvatar">🛹</div><h1 class="center">${esc(r.name)}</h1><p class="center ${r.state==='green'?'online':'offline'}">● ${esc(r.status)}</p><div class="card"><h3>${esc(r.city)}</h3><p>Tabla: ${esc(r.board)}</p><p>Distancia compartida: ${esc(r.km)}</p></div><button class="btn" id="message">💬 Enviar mensaje</button>`);document.querySelector('#back').onclick=map;document.querySelector('#message').onclick=()=>chat(r)}
function chat(r){const history=savedMessages(r.id);shell(`<div class="row spread"><div><div class="brand">CHAT PRIVADO</div><h2>${esc(r.name)}</h2></div><button class="mini" id="back">‹</button></div><div class="chat" id="chat"><div class="bubble them">¿Qué tal? ¿Sales hoy?</div><div class="bubble me">Sí, estaba mirando una ruta 👋</div>${history.map(m=>'<div class="bubble me">'+esc(m.text)+'</div>').join('')}</div><button class="btn voice" id="voice">🎙️ Invitar a Rider Voz</button><div class="composer"><input id="msg" placeholder="Escribe un mensaje..."><button id="send">➤</button></div>`);
document.querySelector('#back').onclick=()=>profile(r.id);const input=document.querySelector('#msg');const send=()=>{const value=input.value.trim();if(!value)return;document.querySelector('#chat').insertAdjacentHTML('beforeend',`<div class="bubble me">${esc(value)}</div>`);saveMessage(r.id,value);input.value='';};document.querySelector('#send').onclick=send;input.onkeydown=e=>{if(e.key==='Enter')send()};document.querySelector('#voice').onclick=()=>voiceInvite(r)}
function voiceInvite(r){shell(`<div class="brand">RIDER VOZ</div><button class="mini" id="back">‹ Chat</button><div class="profileAvatar">🎙️</div><h1 class="center">Invitar a ${esc(r.name)}</h1><p class="sub center">La conversación de voz solo comienza si el otro rider acepta.</p><button class="btn" id="invite">Enviar invitación</button><button class="btn secondary" id="cancel">Cancelar</button>`);const go=()=>chat(r);document.querySelector('#back').onclick=go;document.querySelector('#cancel').onclick=go;document.querySelector('#invite').onclick=()=>{document.querySelector('#invite').textContent='✓ Invitación enviada';document.querySelector('#invite').disabled=true}}
const routes=[{id:1,name:'Casa de Campo Loop',city:'Madrid',km:'18,4',time:'1 h 12 min',level:'Media',author:'Alex Rider',likes:34},{id:2,name:'Turia Night Ride',city:'Valencia',km:'14,8',time:'58 min',level:'Fácil',author:'Marta',likes:21},{id:3,name:'Sevilla Ribera',city:'Sevilla',km:'22,1',time:'1 h 31 min',level:'Media',author:'Dani',likes:47}];
function sharedRoutes(){shell('<div class="brand">RUTAS COMPARTIDAS</div><div class="row spread"><h1>Descubrir rutas</h1><button class="mini" id="back">‹</button></div><p class="sub">Rutas publicadas por la comunidad.</p>'+routes.map(r=>'<button class="card menuCard" data-route="'+r.id+'"><strong>🗺️ '+esc(r.name)+'</strong><small>📍 '+esc(r.city)+' · '+r.km+' km · '+esc(r.level)+'</small><small>🛹 '+esc(r.author)+' · ♥ '+r.likes+'</small></button>').join(''));document.querySelector('#back').onclick=home;document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>routeDetail(+b.dataset.route))}
function routeDetail(id){const r=routes.find(x=>x.id===id);shell('<div class="brand">RUTA COMPARTIDA</div><button class="mini" id="back">‹ Rutas</button><div class="routePreview">⌁</div><h1>'+esc(r.name)+'</h1><p class="sub">📍 '+esc(r.city)+' · por '+esc(r.author)+'</p><div class="stats"><div><b>'+r.km+'</b><small>km</small></div><div><b>'+esc(r.time)+'</b><small>duración</small></div><div><b>'+esc(r.level)+'</b><small>nivel</small></div></div><button class="btn" id="openRoute">🧭 Abrir ruta</button><button class="btn secondary" id="fav">♡ Guardar en favoritas</button>');document.querySelector('#back').onclick=sharedRoutes;const fav=document.querySelector('#fav');if(isFavorite(r.id))fav.textContent='♥ Guardada en favoritas';fav.onclick=e=>{const on=toggleFavorite(r.id);e.currentTarget.textContent=on?'♥ Guardada en favoritas':'♡ Guardar en favoritas'};document.querySelector('#openRoute').onclick=e=>{e.currentTarget.textContent='✓ Ruta preparada';e.currentTarget.disabled=true}}
const challengeData=[{id:1,icon:'⚡',name:'50 km esta semana',desc:'Acumula 50 km en cualquier número de salidas.',progress:32,target:50,unit:'km'},{id:2,icon:'⛰️',name:'Cazador de desnivel',desc:'Suma 1.000 m de desnivel positivo.',progress:640,target:1000,unit:'m'},{id:3,icon:'🧭',name:'Explorador',desc:'Completa 3 rutas nuevas.',progress:1,target:3,unit:'rutas'}];
function challenges(){shell('<div class="brand">RETOS</div><div class="row spread"><h1>Esta semana</h1><button class="mini" id="back">‹</button></div><p class="sub">Objetivos para darle una excusa más a las ruedas.</p>'+challengeData.map(x=>{const pct=Math.min(100,Math.round(x.progress/x.target*100));return '<button class="card menuCard" data-challenge="'+x.id+'"><strong>'+x.icon+' '+esc(x.name)+'</strong><small>'+esc(x.desc)+'</small><span class="progress"><i style="width:'+pct+'%"></i></span><small>'+x.progress+' / '+x.target+' '+esc(x.unit)+' · '+pct+'%</small></button>'}).join(''));document.querySelector('#back').onclick=home;document.querySelectorAll('[data-challenge]').forEach(b=>b.onclick=()=>challengeDetail(+b.dataset.challenge))}
function challengeDetail(id){const x=challengeData.find(v=>v.id===id),pct=Math.min(100,Math.round(x.progress/x.target*100));shell('<div class="brand">RETO</div><button class="mini" id="back">‹ Retos</button><div class="challengeIcon">'+x.icon+'</div><h1 class="center">'+esc(x.name)+'</h1><p class="sub center">'+esc(x.desc)+'</p><div class="bigProgress">'+pct+'%</div><span class="progress"><i style="width:'+pct+'%"></i></span><p class="center">'+x.progress+' / '+x.target+' '+esc(x.unit)+'</p><button class="btn" id="join">Unirme al reto</button>');document.querySelector('#back').onclick=challenges;const join=document.querySelector('#join');if(joinedChallenge(x.id)){join.textContent='✓ Reto activo';join.disabled=true}join.onclick=e=>{joinChallenge(x.id);e.currentTarget.textContent='✓ Reto activo';e.currentTarget.disabled=true}}
function privacy(){shell('<div class="brand">PRIVACIDAD</div><button class="mini" id="back">‹ Mapa</button><h1>Ubicación</h1><div class="card"><h3>Compartir mi ubicación</h3><p id="shareStatus">'+(state.locationSharing?'Activada':'Desactivada')+'</p><button class="btn secondary" id="toggleShare">'+(state.locationSharing?'Desactivar':'Activar')+'</button></div><p class="sub">Al desactivarla dejas de compartir nuevas posiciones. El módulo queda preparado para aplicar después la caducidad de la última ubicación en el servidor.</p>');document.querySelector('#back').onclick=map;document.querySelector('#toggleShare').onclick=()=>{state.locationSharing=!state.locationSharing;saveState();privacy()}}
function myProfile(){const db=dbLoad(),p=db.profile||{alias:'',city:'',board:'eSkate SUV',bio:''};shell('<div class="brand">MI PERFIL RIDER</div><button class="mini" id="back">‹ Comunidad</button><div class="profileAvatar">🛹</div><label class="field">Alias<input id="alias" maxlength="24" value="'+esc(p.alias||'')+'" placeholder="Tu nombre Rider"></label><label class="field">Ciudad<input id="city" maxlength="40" value="'+esc(p.city||'')+'" placeholder="Ciudad"></label><label class="field">Tabla<input id="board" maxlength="40" value="'+esc(p.board||'')+'" placeholder="eSkate SUV"></label><label class="field">Sobre mí<textarea id="bio" maxlength="140" placeholder="Cuéntale algo a la comunidad">'+esc(p.bio||'')+'</textarea></label><button class="btn" id="saveProfile">Guardar perfil</button><p class="sub center" id="saved"></p>');document.querySelector('#back').onclick=home;document.querySelector('#saveProfile').onclick=()=>{const db=dbLoad();db.profile={alias:document.querySelector('#alias').value.trim(),city:document.querySelector('#city').value.trim(),board:document.querySelector('#board').value.trim(),bio:document.querySelector('#bio').value.trim()};dbSave(db);document.querySelector('#saved').textContent='✓ Perfil guardado en este dispositivo'}}
function riderVoice(){shell('<div class="brand">RIDER VOZ</div><div class="row spread"><h1>Conexión de voz</h1><button class="mini" id="back">‹</button></div><p class="sub">Habla con otros riders mientras ruedas. Las invitaciones requieren aceptación.</p><div class="card"><div class="row"><div class="voiceOrb">🎙️</div><div><h3>Sin conexión activa</h3><p>Selecciona un rider para enviar una invitación de voz.</p></div></div></div><button class="btn" id="find">📍 Buscar riders</button><div class="card"><h3>Controles previstos</h3><p>Micrófono · silenciar · volumen · finalizar conexión.</p></div>');document.querySelector('#back').onclick=home;document.querySelector('#find').onclick=consent}
home();